name: Check AsTeRICS Grid Release and Build APK

on:
  schedule:
    - cron: '0 6 1,15 * *'
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Get latest upstream release
        id: get_latest_release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/asterics/AsTeRICS-Grid/releases/latest | jq -r .tag_name)
          echo "latest_tag=$LATEST" >> $GITHUB_OUTPUT

      - name: Get stored version
        id: get_stored
        run: |
          if [ -f .latest_release ]; then
            STORED=$(cat .latest_release)
          else
            STORED="none"
          fi
          echo "stored_tag=$STORED" >> $GITHUB_OUTPUT

      - name: Store new release version
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: echo "${{ steps.get_latest_release.outputs.latest_tag }}" > .latest_release

      - name: Commit version file
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git pull --rebase origin main
          git add .latest_release
          git commit -m "Update release version to ${{ steps.get_latest_release.outputs.latest_tag }}"
          git push

      - name: Build APK from PWA
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        uses: osgioia/pwa-to-apk-action@v1.0.1
        with:
          project-root-folder: "."

      - name: Decode keystore
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: |
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > my-release-key.jks

      - name: Sign APK
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: |
          jarsigner -verbose \
            -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.jks \
            -storepass "${{ secrets.SIGNING_STORE_PASSWORD }}" \
            -keypass "${{ secrets.SIGNING_KEY_PASSWORD }}" \
            ./app-release-unsigned-aligned.apk "${{ secrets.SIGNING_KEY_ALIAS }}"

      - name: Verify APK signature
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: |
          jarsigner -verify -verbose -certs ./output/app-release-unsigned-aligned.apk

      - name: Rename APK with version
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        run: |
          VERSION=${{ steps.get_latest_release.outputs.latest_tag }}
          mv ./output/app-release-unsigned-aligned.apk ./output/AsTeRICS-Grid-${VERSION}.apk

      - name: Release APK
        if: steps.get_latest_release.outputs.latest_tag != steps.get_stored.outputs.stored_tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_latest_release.outputs.latest_tag }}
          name: "APK for AsTeRICS Grid ${{ steps.get_latest_release.outputs.latest_tag }}"
          files: ./output/AsTeRICS-Grid-${{ steps.get_latest_release.outputs.latest_tag }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
